/**
 * OOPSBannerApp UC2 - Banner Display Application
 * 
 * This class demonstrates creation of a visual banner displaying the word OOPS
 * using Ascii art composed of asterisks (*) and spaces. The banner is printed to the
 * console using individual print statements for each line, creating a decorative
 * text effect.
 * 
 * <p> The banner is generated by printing predefined string patterns line by line,
 * where each line contributes to foming the letters O, O, P and S in a stylized format
 * This extends a basic user story by adding visual presentation to a simple message output.
 * <p>
 * 
 * @author Nishitha
 * @version 2.0 
 *  */

public class OOPSBannerApp { 
    // Main method to run banner display
    // Each Character represented in a 7-line format and a width of 9 characters, aligned properly
    // Print each line of the OOPS banner to create the visual effect for the 
    // Message "OOPS" . Construct each line by concatenating the appropriate patterns for each character, 
    // ensuring proper spacing and alignment to form the desired output.
    // Each line corresponds to a row in the banner for the letters O, O, P and S, 
    // using individual print statements for each line.
    public static void main(String[] args) {
        //System.out.println("OOPS");
        // Line 1
        System.out.println(" *****   *****   *****   ***** ");
        System.out.println("*     * *     * *     * *     *");
        System.out.println("*     * *     * *     * *      ");
        System.out.println("*     * *     * *     *  ***** ");
        System.out.println("*     * *     * *     *       *");
        System.out.println("*     * *     * *     * *     *");
        System.out.println(" *****   *****   *****   ***** ");
    }
}
